{% set version = '1.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-venn
  version: {{ version|replace("-", "_") }}

source:
  fn: venn_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/venn_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/venn/venn_{{ version }}.tar.gz
  sha256: 92a12dc2035b8081a3a56bb15905155a29a73700ce94092a898d98ced92a9452

build:
  noarch: generic
  number: 1001

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('venn')"  # [not win]
    - "\"%R%\" -e \"library('venn')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=venn
  license: GPL (>= 2)
  summary: Draws and displays Venn diagrams up to 7 sets, and any Boolean union of set intersections.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
