{% set version = "1.12" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-venn
  version: {{ version|replace("-", "_") }}

source:
  fn: venn_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/venn_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/venn/venn_{{ version }}.tar.gz
  sha256: ed86b69bd99ceea93352a30699a0baba3fd8cdcde907a9476e92be202ad8721d

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-admisc >=0.5
  run:
    - r-base
    - r-admisc >=0.5

test:
  commands:
    - $R -e "library('venn')"  # [not win]
    - "\"%R%\" -e \"library('venn')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=venn
  license: GPL (>= 2)
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary: Draws and displays Venn diagrams up to 7 sets, and any Boolean union of set intersections.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
