appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 1cVy71T3ShznhgbpBvbWjqxbKcecD24f87MbsYlWR4F9YsVR6fldmXRTqlyDeuaCTV2I8OZMI3lxjl4YyfgixZ5l9WHwT+VTE2rNZUtwA+FCeV7ePCpZ5ryXxCETxnJSZ6z5tD+IfRIfbW7b5pESk1raGzXm2DVH4rJiGpBVayOAF7MwhYUBf+2LYfmKBQ3vhoTxlpRQGMdaBM7LJh8p8VVsTmj4oMDmzyVHIKF27ohwQv3Hbe2Aldlhc5ZgqO+SDfZ8/rjVi6JMxRzzCQiZ1Y9uh3GPtQ2U+KhGbYLhFCuUskqOPKnvhA2xQUn1SHp+yRHDwhw8D/zQv9BfardNtq7RivUrQgm6ic0P5IyNU+0C3WxkQU2o2yO0Jw/ybF+cMMtOZc+mK0i9gl7Y0ieOxoGXSal+bGubTGTC0QTQoGwVJpHJbPFg33cTpqmuGC0W0OQA6x3k336uYSie/iYaNX/iuX1nEMADfB9Ul7y0J0bSfsB9yhI9kRi6mlpQHrIU/+iYgWXAjM37jUrjYDSJi8I5nM21N9GfT99F8D0qzLyLoED+0iPgFBdw7T3+B1JrnQfMWVGyRiQ7a7xB8qNHmzBNITuxYSZcl2dBR2Ww40xBTMYFQrNE/GdHc5ZDJaQ+BoChUDpkqm0gG9JWSFRwyK7d288RSKTrAXiqpmSU9EI=
