travis:
  secure:
    BINSTAR_TOKEN: qVMaj6UItBuXycGZhbdwxruqfxsETnKuanQBnDKo0s137EVWOi6fYKVMHsMbi9UP3FF5qY/sPJ1P+p1lbC88oihgySCwZ5JqyZdebe16dZOfAclYF66CdkL86MZ8raxbP7B4s+dAObnVPDAoKRrPazvdJ+shwZW2gUCv3DpC1MKOoFgSlS0v08XIMLw6sT4gX90I8B7n/4PuJONnvsVqQpOONEf2jW+PetgpjLFHVrDwbijucbZ6fuIAWl1Tgcr9dE90hMhCMqS2E3XsyO98hyAyABs5q08CPntIx2eZE+ff/0ido4cXFl81TNLCHc2Au8x8MkQUtAJymRTLIu3GwiG1g+SMKMlWI9QhKwjnS2dZNIAkxcCWSMGhnIGOaLQbUmHomBM2PC7FwC6eQtozl/eC1zexJgGimgORAcq78ec7gdZ0FIN5cXvvRYh2g891E8OojmP5o9LRsUn+ybHOmJ5Y0UjDNcSYuXiRHJ8ZLPfLlsUomhsVLHC7pfDoyHBF5OqVcaacLurACkjimKr1ZNd5C43CpNuhjE48mirYHQgCJRczbpZ+FPhO82ZvTpU3BRgOfOP85cF95upfQ2queT/XTz5y7R/qBIP2KVXiCHmqNHUpoVQsYc2VeyiozTnzQWCJ7jtuqNx767+BeQq3eR3yoDnZniZnqCpAMrwzYa4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
